DROP TABLE IF EXISTS TEST;
CREATE TABLE TEST(ID INT PRIMARY KEY,
   NAME VARCHAR(255),
   STATUS VARCHAR(25));
INSERT INTO TEST VALUES(1, 'Hello','NEW');
INSERT INTO TEST VALUES(2, 'World','NEW');
INSERT INTO TEST VALUES(3, 'World','NEW');
INSERT INTO TEST VALUES(4, 'World','NEW');
INSERT INTO TEST VALUES(5, 'World','NEW');
INSERT INTO TEST VALUES(6, 'World','NEW');
INSERT INTO TEST VALUES(7, 'World','NEW');
INSERT INTO TEST VALUES(8, 'World','NEW');
INSERT INTO TEST VALUES(9, 'World','NEW');
INSERT INTO TEST VALUES(10, 'World','NEW');
INSERT INTO TEST VALUES(11, 'World','NEW');
INSERT INTO TEST VALUES(12, 'World','NEW');
INSERT INTO TEST VALUES(13, 'World','NEW');
INSERT INTO TEST VALUES(14, 'World','NEW');
INSERT INTO TEST VALUES(15, 'World','NEW');
INSERT INTO TEST VALUES(16, 'World','NEW');
INSERT INTO TEST VALUES(17, 'World','NEW');
INSERT INTO TEST VALUES(18, 'World','NEW');
INSERT INTO TEST VALUES(19, 'World','NEW');
INSERT INTO TEST VALUES(20, 'World','NEW');
